In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import sklearn

In [6]:
cleaned_df = pd.read_csv('../data/cleaned_data_source.csv')
cleaned_df

,MSISDN/Number,Bearer Id,Total UL/DL,Total HTTP,Total Youtube,Total Netflix,Total Gaming,Total Google,Total Email,Total Social Media,Total Other,Dur. (ms)
0,3.360100e+10,1,878.690574,117.713325,21.624548,27.180981,812.458661,4.389005,1.0,2.232135,386.570872,116720.0
1,3.360100e+10,1,156.859643,117.713325,12.432223,11.221763,119.750078,5.334863,3.0,2.660565,281.710071,181230.0
2,3.360100e+10,1,595.966483,117.713325,21.333570,19.353900,538.827713,3.443126,3.0,3.195623,501.693672,134969.0
3,3.360101e+10,1,422.320698,0.009402,6.977321,1.942092,391.126127,9.678493,2.0,0.280294,35.279702,49878.0
4,3.360101e+10,2,1457.410944,307.655241,41.533002,49.201724,1314.797820,18.499616,3.0,2.912542,804.804484,37104.0
...,...,...,...,...,...,...,...,...,...,...,...,...
106467,3.379000e+10,1,480.307335,117.713325,19.851572,8.531060,437.003292,5.429705,2.0,0.498569,211.115113,140988.0
106468,4.188282e+10,504,254052.402468,20604.593174,11447.654394,11332.644210,221065.748503,3925.359354,1116.0,932.422807,215011.972057,35399200.0
106469,3.197020e+12,1,232.123971,117.713325,11.959905,26.592300,178.048738,10.438660,1.0,0.715224,470.526473,877385.0
106470,3.370000e+14,1,596.287824,117.713325,36.734940,30.905042,510.142695,9.830617,3.0,0.521566,149.188439,253030.0
106471,8.823970e+14,1,139.153646,117.713325,40.940710,28.846230,43.070260,9.218647,3.0,1.546088,401.360457,869844.0

In [16]:
cleaned_numpy = cleaned_df.to_numpy()
print(cleaned_df.shape[0])

mean_list = []

for i in range(cleaned_df.shape[0]):
    np.mean(cleaned_numpy[i, :])
    mean_list.append(np.mean(cleaned_numpy[i, :]))
# mean_x = np.mean(cleaned_numpy[0,:])
# mean_y = np.mean(cleaned_numpy[1,:])
# mean_z = np.mean(cleaned_df[2,:])

mean_vector = np.array(mean_list)

print('Mean Vector:\n', mean_vector)

106472
Mean Vector:
 [2.80009339e+09 2.80009864e+09 2.80009494e+09 ... 2.66418407e+11
 2.80833334e+13 7.35330834e+13]

In [17]:
scatter_matrix = np.zeros((cleaned_df.shape[0],cleaned_df.shape[1]))
for i in range(cleaned_numpy.shape[1]):
    scatter_matrix += (cleaned_numpy[:,i].reshape(cleaned_df.shape[0],1) - mean_vector).dot((cleaned_numpy[:,i].reshape(cleaned_df.shape[0],1) - mean_vector).T)
print('Scatter Matrix:\n', scatter_matrix)

In [ ]:
cov_mat = np.cov([cleaned_numpy[0,:],cleaned_numpy[1,:],cleaned_numpy[2,:]])
print('Covariance Matrix:\n', cov_mat)